apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-czak
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0049-tenant/tkrw-pr712-0075-0049-app/devfile-sample-czak@sha256:054537f36604f3525891c70899493aad7dda9bb6ec2faadab387cf2c8a3a51a7
        name: my-nodejs
        resources: {}
status: {}
